#!/usr/bin/env python

import sys
import time

messages = [
'announce route 1.1.0.0/24 next-hop 101.1.101.1',
'announce route 1.1.0.0/25 next-hop 101.1.101.1',
'announce route 1.2.0.0/24 next-hop 101.1.101.1',
'announce route 1.3.0.0/25 next-hop 101.1.101.1',
'announce route 1.4.0.0/24 next-hop 101.1.101.1',
'announce route 1.5.0.0/25 next-hop 101.1.101.1',
'announce route 1.6.0.0/24 next-hop 101.1.101.1',
'announce route 1.7.0.0/25 next-hop 101.1.101.1',
'announce route 1.8.0.0/24 next-hop 101.1.101.1',
'announce route 1.9.0.0/25 next-hop 101.1.101.1',
'announce route 1.10.0.0/24 next-hop 101.1.101.1',
'announce route 1.11.0.0/25 next-hop 101.1.101.1',
'announce route 1.12.0.0/24 next-hop 101.1.101.1',
'announce route 1.13.0.0/25 next-hop 101.1.101.1',
'announce route 1.14.0.0/24 next-hop 101.1.101.1',
'announce route 1.15.0.0/25 next-hop 101.1.101.1',
'announce route 1.16.0.0/24 next-hop 101.1.101.1',
'announce route 1.17.0.0/25 next-hop 101.1.101.1',
'announce route 1.18.0.0/24 next-hop 101.1.101.1',
'announce route 1.19.0.0/25 next-hop 101.1.101.1',
'announce route 1.20.0.0/24 next-hop 101.1.101.1',
'announce route 1.21.0.0/25 next-hop 101.1.101.1',
'announce route 1.22.0.0/24 next-hop 101.1.101.1',
'announce route 1.23.0.0/25 next-hop 101.1.101.1',
'announce route 1.24.0.0/24 next-hop 101.1.101.1',
'announce route 1.25.0.0/25 next-hop 101.1.101.1',
]

messages1 = [
'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.1.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.2.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.3.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.4.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.5.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.6.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.7.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.8.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.9.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.10.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.11.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.12.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.13.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.14.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.15.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.16.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.17.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.18.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.19.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.20.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.21.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.22.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.23.0.0/25 next-hop 101.1.101.1',
'withdraw route 1.24.0.0/24 next-hop 101.1.101.1',
'withdraw route 1.25.0.0/25 next-hop 101.1.101.1',
]

time.sleep(2)

# while messages:
#     message = messages.pop(0)
#     sys.stdout.write( message + '\n')
#     sys.stdout.flush()


# time.sleep(10)

# while messages1:
#     message = messages1.pop(0)
#     sys.stdout.write( message + '\n')
#     sys.stdout.flush()

next_hop="192.168.10.3"

for x in range (1, 100):
    for y in range (1, 100):
        sys.stdout.write("announce route "+str(x)+"."+str(y)+".0.0/24 next-hop "+next_hop +'\n')
        sys.stdout.flush()

#sleep(60)

#for x in range (31, 60):
#    for y in range (1, 100):
#        sys.stdout.write("announce route "+str(x)+"."+str(y)+".0.0/24 next-hop "+next_hop +'\n')
#        sys.stdout.flush()


while True:
    time.sleep(1)
